#include "hal_data.h"
#include "S_dev/S_i2c/s_i2c.h"
#include "S_dev/S_uart/s_uart.h"

#include "stdio.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
//    uart_init();
//    i2c_init();
//
//    uint8_t uart_str[] = "SANG\r\n";
//    uint8_t i2c_rx;
//    while(1)
//    {
//        i2c_write_reg(0x88, 0x55);
//        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
//        i2c_read_reg(0x88, &i2c_rx, 1);
//        R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
//
//        uart_send_buf(uart_str, sizeof(uart_str) - 1);
//
//
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_09, 1);
//        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
//        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_09, 0);
//        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
//    }


    uart_init();
    i2c_init();

    uint8_t i2c_rx;
    char uart_buf[32];

    while(1)
    {
        /* Write */
        if (i2c_write_reg(0x88, 0x55) != FSP_SUCCESS)
        {
            uart_send_buf((uint8_t *)"I2C WRITE ERR\r\n", 15);
        }

        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);

        /* Read */
        if (i2c_read_reg(0x88, &i2c_rx, 1) == FSP_SUCCESS)
        {
            int len = sprintf(uart_buf, "RX = 0x%02X\r\n", i2c_rx);
            uart_send_buf((uint8_t *)uart_buf, (uint8_t)len);
        }
        else
        {
            uart_send_buf((uint8_t *)"I2C READ ERR\r\n", 14);
        }

        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);

        /* Blink LED */
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_09, 1);
        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_06_PIN_09, 0);
        R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
    }
















    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
