#include "hal_data.h"
#include "dev/i2c/i2c.h"
#include "dev/uart/uart.h"
#include "dev/zmod4410/zmod4410_adapter.h"

#include "stdio.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    uart_init();
    char uart_str[100];

    i2c0_register_init();
    i2c1_register_init();

    uint8_t zmod_id = i2c0_read_reg(0x32, 0x00);

    if (zmod_id == 0x23)
    {
        int len = snprintf(uart_str, sizeof(uart_str),
                           "ZMOD4410 detected successfully (ID=0x%02X)\r\n", zmod_id);
        uart_send_buf((uint8_t *)uart_str, (uint32_t)len);

        zmod4410_read_iaq();

    }
    else
    {
        int len = snprintf(uart_str, sizeof(uart_str),
                           "Unexpected ID! Read = 0x%02X\r\n", zmod_id);
        uart_send_buf((uint8_t *)uart_str, (uint32_t)len);
    }

    uint8_t rx_buf[3];

    while (1)
    {
        i2c1_read_mult_reg(0x68, 0x00, rx_buf, 3);
        int len = snprintf(uart_str, sizeof(uart_str), "I2C Read [0x68:0x00] = 0x%02X 0x%02X 0x%02X \r\n", rx_buf[0], rx_buf[1], rx_buf[2]);
        uart_send_buf((uint8_t *)uart_str, (uint32_t)len);
        R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_SECONDS);
    }


    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
